version: "3.8"

services:
  postgres:
    image: postgres:14
    container_name: cmpc-postgres
    restart: always
    environment:
      POSTGRES_DB: CMPCLibrary
      POSTGRES_USER: cmpcUser
      POSTGRES_PASSWORD: cmpcUserPassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init-user.sql:/docker-entrypoint-initdb.d/init-user.sql
    networks:
      - cmpc-network

  backend:
    build: ./backend
    container_name: cmpc-backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
    volumes:
      - ./backend/uploads:/app/uploads
    networks:
      - cmpc-network

  frontend:
    build: ./frontend
    container_name: cmpc-frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend
    networks:
      - cmpc-network

volumes:
  postgres_data:

networks:
  cmpc-network:
    driver: bridge
